# Generated by Django 4.1 on 2022-08-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_rename_chat_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
